### ISSUE TITLE
Keyboard/ trackpad not working. HP Notebook - 15-bs1

### ISSUE THREAD

**Issue by sayed001** [DmitriyyyyS/Hackintosh-HP-Laptop-15-da0233ur#1]
Thank you for your hardwork. The efi worked out of the box for my laptop. HP Notebook - 15-bs1xxne

And the only issue is the keyboard/trackpad.

Thank you again !

**Comment by DmitriyyyyS** [comment]
So the kext from this efi did not suit you, try VoodooPS2, or if you have an I2C controller then voodooi2c.

**Comment by sayed001** [comment]
I got it working, by restarting the pc. The only thing is get laptic panics and i have to limit the cpu to cpus=1 . Do you have a work around for this?

**Comment by DmitriyyyyS** [comment]
I understand that your laptop is not the same as in the repository, you can tell me its exact model, and maybe I can help you.

**Comment by sayed001** [comment]
This is my laptop.

https://support.hp.com/id-en/document/c05942104#AbT1

Everything works flawlessly from your efi except the cpus=1

**Comment by sayed001** [comment]
Also if i use the hdmi,the colors of the output is different and un normal , my gpu is intel 620 but still something is worng.

**Comment by DmitriyyyyS** [comment]
The repository has been updated, but this is for HP da0233ur, try maybe there are no more problems with cpus = 1, if the problem remains, you can try to install VoodooTSCSync.kext. And for HDMI, you may need to register a connector.

**Comment by sayed001** [comment]
Wow, it worked. It works no need to limit the cpu anymore. Now i have to fix the hdmi, not sure how to do that.
